# name: Build and Deploy to Google Cloud Run QA

# on:
#   push:
#     branches:
#       - QA

# jobs:
#   setup-build-deploy:
#     name: Setup, Build, and Deploy
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Cloud SDK
#       uses: google-github-actions/setup-gcloud@v0
#       with:
#         project_id: ${{ secrets.GCP_PROJECT_ID }}
#         service_account_key: ${{ secrets.GCP_SA_KEY }}
#         export_default_credentials: true

#     - name: Load environment variables
#       run: |
#         echo "VITE_APP_CLOUDINARY_API_KEY=${{ secrets.VITE_APP_CLOUDINARY_API_KEY }}" >> $GITHUB_ENV
#         echo "VITE_APP_CLOUDINARY_API_SECRET=${{ secrets.VITE_APP_CLOUDINARY_API_SECRET }}" >> $GITHUB_ENV
#         echo "VITE_APP_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_APP_CLOUDINARY_CLOUD_NAME }}" >> $GITHUB_ENV
#         echo "VITE_APP_CLOUDINARY_API_BASE_URL=${{ secrets.VITE_APP_CLOUDINARY_API_BASE_URL }}" >> $GITHUB_ENV
#         echo "VITE_APP_CLOUDINARY_UPLOAD_PRESET=${{ secrets.VITE_APP_CLOUDINARY_UPLOAD_PRESET }}" >> $GITHUB_ENV
#         echo "VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }}" >> $GITHUB_ENV
#         echo "VITE_APP_SECRET_KEY=${{ secrets.VITE_APP_SECRET_KEY }}" >> $GITHUB_ENV
#         echo "VITE_APP_TOKEN=${{ secrets.VITE_APP_TOKEN }}" >> $GITHUB_ENV
#         echo "VITE_APP_REFRESH_TOKEN=${{ secrets.VITE_APP_REFRESH_TOKEN }}" >> $GITHUB_ENV
#         echo "VITE_APP_USER_INFO=${{ secrets.VITE_APP_USER_INFO }}" >> $GITHUB_ENV

#     - name: Build and push Docker image
#       run: |
#         gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/langeasy-frontend-qa:${GITHUB_SHA} . || echo "Build submitted, unable to stream logs"

#     - name: Deploy to Cloud Run
#       run: |
#         gcloud run deploy langeasy-frontend-qa \
#           --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/langeasy-frontend-qa:${GITHUB_SHA} \
#           --platform managed \
#           --region us-central1 \
#           --allow-unauthenticated \
#           --update-env-vars VITE_APP_CLOUDINARY_API_KEY=${{ secrets.VITE_APP_CLOUDINARY_API_KEY }},VITE_APP_CLOUDINARY_API_SECRET=${{ secrets.VITE_APP_CLOUDINARY_API_SECRET }},VITE_APP_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_APP_CLOUDINARY_CLOUD_NAME }},VITE_APP_CLOUDINARY_API_BASE_URL=${{ secrets.VITE_APP_CLOUDINARY_API_BASE_URL }},VITE_APP_CLOUDINARY_UPLOAD_PRESET=${{ secrets.VITE_APP_CLOUDINARY_UPLOAD_PRESET }},VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }},VITE_APP_SECRET_KEY=${{ secrets.VITE_APP_SECRET_KEY }},VITE_APP_TOKEN=${{ secrets.VITE_APP_TOKEN }},VITE_APP_REFRESH_TOKEN=${{ secrets.VITE_APP_REFRESH_TOKEN }},VITE_APP_USER_INFO=${{ secrets.VITE_APP_USER_INFO }}

















name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - QA
      - main

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Load environment variables
      run: |
        echo "VITE_APP_CLOUDINARY_API_KEY=${{ secrets.VITE_APP_CLOUDINARY_API_KEY }}" >> $GITHUB_ENV
        echo "VITE_APP_CLOUDINARY_API_SECRET=${{ secrets.VITE_APP_CLOUDINARY_API_SECRET }}" >> $GITHUB_ENV
        # ... Load other variables similarly

    - name: Determine suffix, tag, and service name
      run: |
        echo "Branch Ref: ${{ github.ref }}"
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          suffix=""
          service="langeasy-frontend"
        else
          suffix="-qa"
          service="langeasy-frontend-qa"
        fi
        tag="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${service}:${GITHUB_SHA}"
        echo "Service name: $service"
        echo "Tag: $tag"
        echo "suffix=${suffix}" >> $GITHUB_ENV
        echo "service=${service}" >> $GITHUB_ENV
        echo "tag=${tag}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag ${{ env.tag }} .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.service }} \
          --image ${{ env.tag }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --update-env-vars VITE_APP_CLOUDINARY_API_KEY=${{ secrets.VITE_APP_CLOUDINARY_API_KEY }},VITE_APP_CLOUDINARY_API_SECRET=${{ secrets.VITE_APP_CLOUDINARY_API_SECRET }},VITE_APP_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_APP_CLOUDINARY_CLOUD_NAME }},VITE_APP_CLOUDINARY_API_BASE_URL=${{ secrets.VITE_APP_CLOUDINARY_API_BASE_URL }},VITE_APP_CLOUDINARY_UPLOAD_PRESET=${{ secrets.VITE_APP_CLOUDINARY_UPLOAD_PRESET }},VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }},VITE_APP_SECRET_KEY=${{ secrets.VITE_APP_SECRET_KEY }},VITE_APP_TOKEN=${{ secrets.VITE_APP_TOKEN }},VITE_APP_REFRESH_TOKEN=${{ secrets.VITE_APP_REFRESH_TOKEN }},VITE_APP_USER_INFO=${{ secrets.VITE_APP_USER_INFO }}












